## the planner configurations; each config must have a type, which specifies
## the planner to be used; other parameters can be specified as well, depending 
## on the planner

right_arm:
  planner_configs:
    - SBLkConfigDefault
    - SBLkConfig1
    - SBLkConfig2
    - SBLkConfig3  
    - SBLkConfig4
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTConnectkConfigD
    - RRTConnectkConfigH
    - RRTConnectkConfigDH
    - RRTConnectkConfigDD
    - SBLkConfigDefaultD
    - SBLkConfigDefaultDD
    - SBLkConfigDefaultDH
    - SBLkConfigDefaultH
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
  projection_evaluator: joints(r_shoulder_pan_joint,r_shoulder_lift_joint)
  longest_valid_segment_fraction: 0.1

left_arm: 
  planner_configs:
    - SBLkConfigDefault 
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
  projection_evaluator: link(l_wrist_roll_link)
  longest_valid_segment_fraction: 0.05

arms:
  planner_configs:
    - SBLkConfigDefault 
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
  longest_valid_segment_fraction: 0.05
  projection_evaluator: joints(r_shoulder_pan_joint,l_shoulder_pan_joint)

planner_configs:

  SBLkConfigDefaultH:
    type: geometric::SBL
    range: 3.5

  SBLkConfigDefaultD:
    type: geometric::SBL
    range: 14

  SBLkConfigDefaultDD:
    type: geometric::SBL
    range: 28

  SBLkConfigDefaultDH:
    type: geometric::SBL
    range: 21

  SBLkConfigDefault:
    type: geometric::SBL

  SBLkConfig1:
    type: geometric::SBL
    projection_evaluator: link(r_wrist_roll_link)

  SBLkConfig2:
    type: geometric::SBL
    projection_evaluator: joints(r_shoulder_pan_joint,r_wrist_flex_joint)
  
  SBLkConfig3:
    type: geometric::SBL
    projection.cellsize_factor: 0.5

  SBLkConfig4:
    type: geometric::SBL
    projection_evaluator: link(r_wrist_roll_link)
    projection.cellsize_factor: 10

  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    
  RRTkConfigDefault:
    type: geometric::RRT

  RRTConnectkConfigH:
    type: geometric::RRTConnect
    range: 3.5

  RRTConnectkConfigD:
    type: geometric::RRTConnect
    range: 14

  RRTConnectkConfigDH:
    type: geometric::RRTConnect
    range: 21

  RRTConnectkConfigDD:
    type: geometric::RRTConnect
    range: 28

  RRTConnectkConfigDefault:
    type: geometric::RRTConnect

  LazyRRTkConfigDefault:
    type: geometric::LazyRRT

  ESTkConfigDefault:
    type: geometric::EST

  KPIECEkConfigDefault:
    type: geometric::KPIECE

  RRTStarkConfigDefault:
    type: geometric::RRTStar

  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
