# for now expects either "arms" or "right_arm"
group_name: arms

benchmark_service: /benchmark_planning_problem
world_frame: map
robot_model_root_frame: odom
spine_frame: torso_lift_link
experiment_group_name: dual_tabletop

# of calls to the planner per experiment
average_count: 1

# list the planner_interfaces you want to benchmark with
# the benchmark server includes the ompl by default
planner_interfaces: 
  SBPLPlanner
#  SBLkConfigDefault

goal_tolerance:
  xyz: 0.02 0.02 0.02
  rpy: 0.05 0.05 0.05

# true: use the last waypoint in the previous experiment's trajectory as the start state for the next experiment 
# false: use the start state specified in the experiment description as the start state of that experiment
use_current_pose_as_start_state: false

#collision_object_offset:
#  xyz: -1.28 -0.9 0
#  rpy: 0 0.0 0

# only used for both_arms experiments
# this is currently needed to be on the param server for the single arm experiments as well :)
# pose of {r,l}_wrist_roll_links in the object frame
object_pose_in_gripper:
  right:
    xyz: 0 -0.36 0
    rpy: 1.57 0 1.57
  left:
    xyz: 0 0.36 0
    rpy: 1.57 0 -1.57

initial_start_state:
  right: -0.657967 0.888673 -1.4311 -1.073419 -0.705232 -1.107079 2.806742 
  left: 0.848628 0.7797 1.396294 -0.828274 0.687905 -1.518703 0.394348
  base: 0 0 0
  spine: 0.0

#  right: 0 0.017997624551430391 -0.005238188295824564 -0.43192349103359273 -0.00041708680445573521 -0.74471175505726084 -0.0010002085575777642
#  left: 0 0.018023182385653591 0.005683010665493704 -0.43150111655319634 0.00079943310185193195 -0.7439117804053561 0.00049889278955195238
#  base: 0 0 0
#  spine: 0.1



