experiments:

  - name: exp1
    goal: goal1
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: exp2
    goal: goal2
    pre_action: nothing
    post_action: nothing
    sound_bite: "testing is fun!"
  - name: exp3
    goal: goal3
    pre_action: nothing
    post_action: nothing
    sound_bite: "I'm havin a grand ol' time"
  - name: exp4
    goal: goal4
    pre_action: nothing
    post_action: nothing
    sound_bite: "Can't stop now!"

