experiments:

  - name: exp1
    goal: goal1
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: exp2
    goal: goal2
    pre_action: nothing
    post_action: nothing
    sound_bite: "testing is fun!"


