experiments:

  - name: industrial_01
    goal: oven_01
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: industrial_02
    goal: top_bin_left_01
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: industrial_03
    goal: oven_01
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: industrial_04
    goal: top_bin_right_01
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: industrial_05
    goal: oven_01
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"
  - name: industrial_06
    goal: top_bin_right_02
    pre_action: nothing
    post_action: nothing
    sound_bite: "how ya doin buddy?"

