locations:

  - name: goal1
    pose: 0.6 -0.4 0.86 1.0 0.26 0.18
  - name: goal2
    pose: 0.4 1.0 0.25 0 0 0
  - name: goal3
    pose: 0.4 1.6 0.25 0 0 0
  - name: goal4
    pose: 0.4 0.4 0.7 0 0 0

